#-------------------------------------------------------------------#
#
#   OS/tools source code compile rules
#
#   (c) Copyright OS/tools Incorporated 1999
#
#   Author: Francisco J. O'Meany
#
#-------------------------------------------------------------------#

SRCPATH  = D:\UNIVERSE\OSTCLTST
LIBPATH  = D:\UNIVERSE\OSTCLTST
INCPATH  = D:\UNIVERSE\OSTCLTST
INCOTHER = C:\IBMCPP\INCLUDE\SYS

#-- !CMDSWITCHES +D



