#define DID_NULL             0
#define DID_CLEAR          300
#define DID_HELP           301
#define DID_INSTALL        302
#define DID_DELETE         303
#define DID_INSERT         304
#define DID_OEM            305
#define DID_UPDATE         306

#define BSZ_DLG            600
#define BSZ_LENGTH         601
#define BSZ_LENGTHT        602
#define BSZ_MINLEN         603
#define BSZ_MAXLEN         604
#define BSZ_WRAP           605
#define BSZ_STOP           606
#define BSZ_FILE           607

#define HWS_DLG           1600
#define HWS_COMEVENT      1601
#define HWS_COMERROR      1602
#define HWS_XMITST        1603
#define HWS_COMST         1604
#define HWS_DTR           1605
#define HWS_RTS           1606
#define HWS_DCD           1607
#define HWS_DSR           1608
#define HWS_CTS           1609
#define HWS_RCVBUFLEN     1611
#define HWS_XMITBUFLEN    1612
#define HWS_XMITBUFLEV    1613
#define HWS_RING          1615
#define HWS_UPDATE        1616
#define HWSDS_DLG         1617
#define HWSCS_DLG         1618
#define HWSRB_DLG         1619
#define HWSTB_DLG         1620
#define HWSIS_DLG         1621
#define HWSOS_DLG         1622
#define HWSUD_DLG         1623
#define HWS_RCVBUFLEV     1624

#define V_HWSDS_DLG        1650
#define V_HWSIS_DLG        1651
#define V_HWSOS_DLG        1652
#define V_HWS_BUFF_DLG     1653
#define V_HWS_TX_BUFF_DLG  1654

#define ABT_ICON           1700

#define IDM_COMSCOPE    2000
#define IDM_DEVICE      2001
#define IDM_FILE        2002
#define IDM_LOADDAT     2003
#define IDM_SAVEDAT     2004
#define IDM_SETUP       2005
#define IDM_VIEWDAT     2006
#define IDM_SAVEDATAS   2007
#define IDM_SAVEONEXIT  2008

#define IDM_MSTREAM     2009
#define IDM_BAUDRATE    2010
#define IDM_FILTER      2011
#define IDM_TIMEOUT     2012
#define IDM_EXIT        2013

#define IDM_ACTION      2014

#define IDM_MDISPLAY    2019
#define IDM_MSLEEP      2020

#define IDM_SSELECT     2021
#define IDM_INSTALL     2022

#define IDM_HANDSHAKE   2023
#define IDM_FIFO        2024
#define IDM_PROTO       2025

#define IDM_PDEFINE     2026
#define IDM_PSELECT     2027

#define IDM_OPTION      2028
#define IDM_ERRDISP     2029
#define IDM_HILITE_IMM  2030

#define IDM_IOCTL       2031
#define IDM_FORCEXX     2032
#define IDM_FXON        2033
#define IDM_FXOFF       2034
#define IDM_SENDXX      2035
#define IDM_SXON        2036
#define IDM_SXOFF       2037
#define IDM_SENDBRK     2038
#define IDM_FLUSH       2039
#define IDM_FINPUT      2040
#define IDM_FOUTPUT     2041
#define IDM_FBOTH       2042
#define IDM_SENDIMM     2043

#define IDM_STATUS      2044

#define IDM_STALL       2045
#define IDM_STDEVDRV    2046
#define IDM_STINMDM     2047
#define IDM_STOUTMDM    2048
#define IDM_STRCVBUFF   2049
#define IDM_STXMITBUF   2050
#define IDM_STUPDATE    2051

#define IDM_BUFFSIZE    2053
#define IDM_DISP_TYPE   2055

#define IDM_CFG         2056
#define IDM_PCFG        2057
#define IDM_PCFG_BUFF   2058

#define IDM_COMPRESS    2059

#define IDM_HELP        2060
#define IDM_HELPINDEX   2061
#define IDM_HELPEXTEND  2062
#define IDM_HELPFORHELP 2063
#define IDM_HELPABOUT   2064
#define IDM_HELPKEYS    2065

#define IDM_MANAGE_CFG  2066

#define IDM_ROWS        2067
#define IDM_COLUMNS     2068
#define IDM_TOGGLE_FORMAT 2069
#define IDM_TOGGLE_FONT 2070
#define IDM_NEXT_MENU   2071

#define IDM_OUT1        2072
#define IDM_SHOWCOUNTS  2073
#define IDM_STICKY_MENUS 2074

#define IDM_SURFACE     2075
#define IDM_SURFACE_THIS 2076
#define IDM_SURFACE_ALL 2077

#define IDM_TOGGLE_FONT_SIZE 2078
#define IDM_SILENT_STATUS 2079
#define IDM_CAP_EVENT     2080
#define IDM_TRIGGER       2081
#define IDM_ROW_DISP      2082
#define IDM_COL_DISP      2083
#define IDM_STATUS_DISP   2084
#define IDM_DISPLAY       2085
#define IDM_SEARCH        2086
#define IDM_SEARCH_NEXT   2087
#define IDM_QUERY_INDEX   2088
#define IDM_ITEM_INFO     2089

//#define WIN_COMSCOPE 2000
#define CER_DLG           2600
#define CER_BIT0          2601
#define CER_BIT1          2602
#define CER_BIT2          2603
#define CER_BIT3          2604

#define TST_DLG           2700
#define TST_BIT0          2701
#define TST_BIT1          2702
#define TST_BIT3          2704
#define TST_BIT2          2703
#define TST_BIT4          2705
#define TST_BIT5          2706

#define CEV_DLG           2800
#define CEV_BIT0          2801
#define CEV_BIT1          2802
#define CEV_BIT2          2803
#define CEV_BIT3          2804
#define CEV_BIT4          2805
#define CEV_BIT5          2806
#define CEV_BIT6          2807
#define CEV_BIT7          2808
#define CEV_BIT8          2809

#define CST_BIT0          2901
#define CST_BIT1          2902
#define CST_BIT2          2903
#define CST_BIT3          2904
#define CST_BIT4          2905
#define CST_BIT5          2906
#define CST_BIT6          2907
#define CST_BIT7          2908
#define CST_DLG           2900

#define DLG_ABOUTBOX        2990

#define MSLEEP_DLG          3000
#define MSLEEP_COUNT        3001
#define MSLEEP_USER         3002
#define MSLEEP_CALC         3003
#define MSLEEP_USER_COUNT   3004
#define MSLEEP_USER_COUNTT  3005
#define MSLEEP_BUFF_SIZE    3006
#define MSLEEP_CALC_RATE    3007
#define MSLEEP_WARNING      3009
#define MSLEEP_WARNING1     3010

#define IDM_DISPLAY_OPT     3060
#define IDM_STATUS_DISPLAY  3061

#define DCB_PACKET_DLG    3100
#define DCB_WRT_TO        3101
#define DCB_WRT_TOT       3102
#define DCB_READ_TOT      3104
#define DCB_READ_TO       3103
#define DCB_WRT_TOPROC    3105
#define DCB_WRT_TOPROCT   3106
#define DCB_READ_TOPROCT  3108
#define DCB_READ_TOPROC   3109
#define DCB_CTS_OUT_HS    3121
#define DCB_DSR_OUT_HS    3122
#define DCB_DCD_OUT_HS    3123
#define DCB_DSR_IN_SENSE  3125
#define DCB_RTS_HS        3130
#define DCB_DTR_HS        3131
#define DCB_PACKET_CAP    3132
#define DCB_ERR_REP       3140
#define DCB_BRK_REP       3141
#define DCB_NULL_STRIP    3144
#define DCB_ERR_CHAR      3145
#define DCB_BRK_CHAR      3146
#define DCB_XOFF_CHAR     3147
#define DCB_XON_CHAR      3148
#define DCB_FULLDUP       3149
#define DCB_TX_XON_HS     3150
#define DCB_RX_XON_HS     3151
#define DCB_TITLE         3159
#define DCB_FIFO          3160
#define DCB_RX_FIFO       3161
#define DCB_TX_FIFO       3163

/* pop-up menu defines */
#define IDMPU_STATUS_POPUP       4000
#define IDMPU_ROW_DISP_POPUP     4001
#define IDMPU_COL_DISP_POPUP     4002
#define IDMPU_LAST_MSG           4003
#define IDMPU_COLORS             4004
#define IDMPU_REFRESH            4005
#define IDMPU_SYNC               4006
#define IDMPU_FONT               4007
#define IDMPU_ASCII_FONT         4008
#define IDMPU_HEX_FONT           4009
#define IDMPU_DISP_FILTERS       4010
#define IDMPU_LOCK_WIDTH         4011
#define IDMPU_READ_COLOR         4012
#define IDMPU_WRITE_COLOR        4013
#define IDMPU_COMI_MSG           4014
#define IDMPU_MOVE_WIN           4016
#define IDMPU_LAST_COUNT         4017
#define IDMPU_SILENT_STATUS      4018
#define IDMPU_SIG_DISP_POPUP     4019
#define IDMPU_EVENT_DISP         4020
#define IDMPU_MODEMIN_COLOR      4021
#define IDMPU_MODEMOUT_COLOR     4022
#define IDMPU_OPEN_COLOR         4023
#define IDMPU_WRITEREQ_COLOR     4024
#define IDMPU_READREQ_COLOR      4025
#define IDMPU_DEVIOCTL_COLOR     4026
#define IDMPU_ERROR_COLOR        4027
#define IDMPU_RX_DISP_FILTERS    4028
#define IDMPU_TX_DISP_FILTERS    4029
#define IDMPU_RX_COLORS          4030
#define IDMPU_TX_COLORS          4031
#define IDMPU_RX_LOCK_WIDTH      4032
#define IDMPU_TX_LOCK_WIDTH      4033
#define IDMPU_RX_ASCII_FONT      4036
#define IDMPU_TX_ASCII_FONT      4037
#define IDMPU_RX_HEX_FONT        4038
#define IDMPU_TX_HEX_FONT        4039
#define IDMPU_SYNC_RX            4040
#define IDMPU_SYNC_TX            4041
#define IDM_ROW_DISPLAY          4042
#define IDM_COL_DISPLAY          4043
#define IDMPU_LEX_ASCII_FONT     4044
#define IDMPU_LEX_HEX_FONT       4045

#define COMSCOPE_VERSION  4100

#define DISP_SETUP_DLG    5100
#define DISP_COL_GP       5101
#define DISP_ROW_GP       5102
#define DISP_COL          5103
#define DISP_ROW          5104
#define DISP_ROW_ASCII    5105
#define DISP_COL_ASCII    5106
#define DISP_COL_HEX      5107
#define DISP_ROW_HEX      5108
#define DISP_COL_XMIT     5109
#define DISP_COL_RCV      5111
#define DISP_COL_WRT_NL   5110
#define DISP_WRT_NL       5112
#define DISP_WRT_SKP      5115
#define DISP_WRT_NLT      5116
#define DISP_WRT_FILTER   5117
#define DISP_WRT_FILTERT  5119
#define DISP_WRT_ALPHA    5120
#define DISP_WRT_NUMS     5121
#define DISP_WRT_PUNCT    5122
#define DISP_WRT_NPRINT   5124
#define DISP_RCV_FILTERT  5125
#define DISP_VIRT_LINE    5126
#define DISP_HOR_LINE     5127
#define DISP_RCV_SKP      5128
#define DISP_WRT_NL_CHAR  5129
#define DISP_RCV_FILTER   5130
#define DISP_RCV_NLT      5131
#define DISP_RCV_NL       5132
#define DISP_RCV_NL_CHAR  5133
#define DISP_TYPET        5134
#define DISP_RCV_NLTTT    5135
#define DISP_RCV_NLTT     5136
#define DISP_WRT_NLTT     5137
#define DISP_WRT_NLTTT    5138
#define DISP_WRT_COLT     5139
#define DISP_RCV_COLT     5140
#define DISP_ROWT         5141
#define DISP_COMPRESS     5142
#define DISP_HILITE       5143
#define DISP_RCV_ALPHA    5144
#define DISP_RCV_NUMS     5145
#define DISP_RCV_PUNCT    5146
#define DISP_RCV_NPRINT   5147
#define DISP_SETUP_DLG_CAPTION  5148
#define DISP_SYNC_NONE    5149
#define DISP_SYNC_WRT     5150
#define DISP_SYNC_RCV     5151
#define DISP_SYNCT        5152
#define DISP_ROWTT        5153

#define CLR_DLG           5300
#define CLR_DLG_CAPTION   5301
#define CLR_FWHITE        5302
#define CLR_FBLACK        5303
#define CLR_FBLUE         5304
#define CLR_FRED          5305
#define CLR_FPINK         5306
#define CLR_FGREEN        5307
#define CLR_FCYAN         5308
#define CLR_FYELLOW       5309
#define CLR_FBROWN        5310
#define CLR_FNEUTRAL      5311
#define CLR_FDGRAY        5312
#define CLR_FDBLUE        5313
#define CLR_FDRED         5314
#define CLR_FDPINK        5315
#define CLR_FDGREEN       5316
#define CLR_FDCYAN        5317
#define CLR_FGRAY         5318
#define CLR_BWHITE        5319
#define CLR_BBLACK        5320
#define CLR_BBLUE         5321
#define CLR_BRED          5322
#define CLR_BPINK         5323
#define CLR_BGREEN        5324
#define CLR_BCYAN         5325
#define CLR_BYELLOW       5326
#define CLR_BBROWN        5327
#define CLR_BNEUTRAL      5328
#define CLR_BDGRAY        5329
#define CLR_BDBLUE        5330
#define CLR_BDRED         5331
#define CLR_BDPINK        5332
#define CLR_BDGREEN       5333
#define CLR_BDCYAN        5334
#define CLR_BGRAY         5335
#define CLR_FBACK         5336
#define CLR_BBACK         5337

#define DID_RCVCOLCLR     5350
#define DID_WRTCLR        5351
#define DID_RCVCLR        5352
#define DID_WRTCOLCLR     5354
#define DISP_ROW_COLT     5355

#define DID_AUTOFOREGRND  5401
#define DID_AUTOBACKGRND  5402

#define DISP_FILTER_DLG      6000
#define DISP_CHAR_MASKT      6001
#define DISP_CHAR_MASKTTT    6002
#define DISP_CHAR_MASKTT     6003
#define DISP_CHAR_MASK       6004
#define DISP_NLTTT           6005
#define DISP_NLTT            6006
#define DISP_NL_CHAR         6007
#define DISP_NLT             6008
#define DISP_SKP             6009
#define DISP_FILTER          6010
#define DISP_NL              6011
#define DISP_ALPHA           6012
#define DISP_NUMS            6013
#define DISP_PUNCT           6014
#define DISP_NPRINT          6015
#define DISP_FILTERT         6016
#define DISP_WRAP            6017
#define DISP_FILTER_CAPTION  6018
#define DISP_SYNC            6019
#define DISP_ROW_CLRT        6020

#define CLR_SAMPLE          6400
#define COMI_VERSION        6402

#define FIND_DLG          6500
#define FIND_STR_NONE     6501
#define FIND_STR_TX       6502
#define FIND_STR_RX       6503
#define FIND_STR          6504
#define FIND_STR_ASCII    6505
#define FIND_STR_HEX      6506
#define FIND_STR_DEC      6507
#define FIND_MODEMOUT     6510
#define FIND_MODEMIN      6511
#define FIND_DEVIOCTL     6515
#define FIND_IMM          6516
#define FIND_WRITE_REQ    6517
#define FIND_READ_REQ     6518
#define FIND_ERRORS       6520
#define FIND_OPEN         6521
#define FIND_PREVIOUS     6525
#define FIND_NEXT         6526
#define FIND_WRAP         6527
#define FIND_XMIT         6528
#define FIND_RCV          6529
#define FIND_STR_NO_CASE  6530

#define EVENT_DISP_DLG      7000
#define EVENT_RCV           7001
#define EVENT_XMIT          7002
#define EVENT_IMM           7003
#define EVENT_OPEN          7006
#define EVENT_MODEMIN       7004
#define EVENT_MODEMOUT      7005
#define EVENT_WRITE_REQ     7007
#define EVENT_READ_REQ      7008
#define EVENT_DEVIOCTL      7009
#define EVENT_DISP_HILIGHT  7010
#define EVENT_DISP_COMPRESS 7011
#define EVENT_DISP_STREAMT  7012
#define EVENT_ERRORS        7013
#define EVENT_POPUP_PARAMS  7014

#define TRACE_DLG          8000
#define TRACE_RCV          8001
#define TRACE_XMIT         8002
#define TRACE_IMM          8003
#define TRACE_MODEM_IN     8004
#define TRACE_MODEM_OUT    8005
#define TRACE_OPEN_CLOSE   8006
#define TRACE_WRITE_REQ    8007
#define TRACE_READ_REQ     8008
#define TRACE_DEVIOCTL     8009
#define TRACE_ERRORS       8010
#define TRACE_FUNC_PARAMS  8011

#define HWM_DLG          9000
#define HWM_DTRT         9001
#define HWM_DTR_ON      9002
#define HWM_DTR_OFF     9003
#define HWM_RTST        9004
#define HWM_RTS_ON      9005
#define HWM_RTS_OFF     9006
#define HWM_OUT1T       9007
#define HWM_OUT1_ON     9010
#define HWM_OUT1_OFF    9011
#define HWM_CAPTION     9012

#define DLG_COUNTS      9100
#define CAP_COUNTS      9101
#define CB_DISPCPS      9102
#define CB_DISPCOUNTS   9105
#define ST_TITLE        9107
#define SPB_SAMPLES     9108

#define TRIG_DLG          19000
#define TRIG_END_RTS      19010
#define TRIG_END_DTR      19011
#define TRIG_END_CTS      19012
#define TRIG_END_DSR      19013
#define TRIG_END_DCD      19014
#define TRIG_BEG_RTS      19015
#define TRIG_BEG_DTR      19016
#define TRIG_BEG_CTS      19017
#define TRIG_BEG_DSR      19018
#define TRIG_BEG_DCD      19019
#define TRIG_BEG_ASCII    19021
#define TRIG_BEG_HEX      19020
#define TRIG_BEG_RI       19021
#define PB_ALL            19022
#define TRIG_             19023
#define TRIG_ENABLE       19030
#define TRIG_BEG_TX       19040
#define TRIG_BEG_RX       19041
#define TRIG_END_TX       19042
#define TRIG_END_RX       19043
#define TRIG_END_TX_ENAB  19045
#define TRIG_END_RX_ENAB  19046
#define TRIG_BEG_RX_ENAB  19047
#define TRIG_BEG_TX_ENAB  19048
#define TRIG_BEG_TXT      19050
#define TRIG_BEG_RXT      19051
#define TRIG_END_TXT      19052
#define TRIG_END_RXT      19054
#define TRIG_END_ASCII    19057
#define TRIG_END_HEX      19056

#define TRIG_BEG_COUNT    19060
#define TRIG_BEG_EACH     19062
#define TRIG_BEG_RESTART  19063
#define TRIG_BEG_REARM    19064
#define TRIG_END_COUNT    19070
#define TRIG_END_REARM    19071

#define HWS_BUFLEN        19090
#define HWS_BUFHIGH       19091
#define HWS_BUFLEV        19092
#define HWS_TX_BUFF_DLG   19093
#define HWS_BUFF_DLG      19094
#define HWS_BUFF_CAP      19095


#define ST_COPYRIGHT       19202

/* Menu defines */

#define ST_ANDIS             19300
#define TRIG_END_RI          19301
#define ST_SAMPLES           19302
#define ST_GILROYCALIFORNIA  19303
#define ST_INTERNETPRODUCTS  19304
#define ST_TELEPHONENUM      19305
#define IDM_ROW_POPUP 19306
